### ISSUE TITLE
Game wont launch with update 3.0.9 (no logs)

### ISSUE THREAD

**Issue by SLdonny** [ThirteenAG/GTAIV.EFLC.FusionFix#615]
### Game version this happens in

v1.2.0.59

### What area of the game

installed new update, launched the game and nothing happens but gta 4 appears in task manager for a split second.. 
was working before i updated, not gettin no crash logs or nun of that
   game version 1.0.7.0

### What should happen

game opening

### Last working version

not sure last version i had before 3.0.9 was downloaded bout a month ago

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by SLdonny** [comment]
managed to get a crash log by spamming the exe

Unhandled exception at 0x76BAA892 in KERNELBASE.dll (+0x14a892): 0xE0434352: NO_DESCRIPTION.
    Register dump:
        EAX: 0x054CEB68  EBX: 0x00000005  ECX: 0x00000005  EDX: 0x00000000  
        EDI: 0x00000001  ESI: 0x054CEC28  EBP: 0x054CEBC0  EIP: 0x76BAA892  
        ESP: 0x054CEB68  EFL: 0x00000212  
        
        CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   
        ES: 0x0000002B   DS: 0x0000002B   
        
        ST00: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST01: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST02: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST03: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST04: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST05: 0x00000000 0x80000000 0x00003FFF 0x40000000  [ 0.000000 -0.000000 0.000000 2.000000 ]
        ST06: 0x00000000 0xF8814000 0x00004006 0x00000000  [ 0.000000 -20972011530175827218361457829740544.000000 0.000000 0.000000 ]
        ST07: 0x00000000 0x80000000 0x00003FFF 0x002B0000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        
        XMM00: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM01: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM02: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM03: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM04: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM05: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM06: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM07: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        
    Stack dump:
        0x054CEB68:  E0434352 00000001 00000000 76BAA892 00000005 80070002
        0x054CEB80:  00000000 00000000 00000000 73BE0000 054F46B8 054CFE0C
        0x054CEB98:  00000001 00000048 00000001 00000048 00000001 76F210F0
        0x054CEBB0:  054CEBB0 054CEB88 054F46B8 1C8B3ED1 054CEC5C 73D6B88F
        0x054CEBC8:  E0434352 00000001 00000005 054CEC28 0ECCB70B 07A897C0
        0x054CEBE0:  059E50B4 054CED18 054F46B8 00000001 E0434352 00000000
        0x054CEBF8:  07A897C0 73C0F080 054CEC0C 73C0F09D 07A897C0 054CDF18
        0x054CEC10:  054CEC1C E0434352 E0434352 00000000 059E50B4 00000000
        0x054CEC28:  80070002 00000000 00000000 00000000 73BE0000 054F46B8
        0x054CEC40:  054F4844 054CEBD8 054CDF18 054CEC84 73D4E5F0 7856E3E7
        base: 0x053D0000   top: 0x054CEB68   bottom: 0x054D0000
        
    Backtrace (may be wrong):
        =>0x76BAA892 RaiseException+0x62 in KERNELBASE.dll (+0x14a892) (0x054CEBC0) 
          0x73D6B88F CorDllMainForThunk+0x853f in clr.dll (+0x18b88f) (0x054CEC5C) 
          0x73E96130 GetPermissionRequests+0x22ac0 in clr.dll (+0x2b6130) (0x054CEC90) 
          0x73EC5526 GetHistoryFileDirectory+0x12886 in clr.dll (+0x2e5526) (0x054CED24) 
          0x70E443BC in clrjit.dll (+0x143bc) (0x054CED3C) 
          0x70E3A5BE in clrjit.dll (+0xa5be) (0x054CF4DC) 
          0x70E444E0 in clrjit.dll (+0x144e0) (0x054CF564) 
          0x70E446AB in clrjit.dll (+0x146ab) (0x054CF57C) 
          0x70E44713 in clrjit.dll (+0x14713) (0x054CF598) 
          0x70E45ED7 in clrjit.dll (+0x15ed7) (0x054CF5D8) 
          0x70E42468 in clrjit.dll (+0x12468) (0x054CF650) 
          0x70E425BE in clrjit.dll (+0x125be) (0x054CF750) 
          0x70E4A77D in clrjit.dll (+0x1a77d) (0x054CF798) 
          0x73CB7875 PreBindAssemblyEx+0x39cf5 in clr.dll (+0xd7875) (0x054CF7F4) 
          0x73CB7945 PreBindAssemblyEx+0x39dc5 in clr.dll (+0xd7945) (0x054CF83C) 
          0x73CB799A PreBindAssemblyEx+0x39e1a in clr.dll (+0xd799a) (0x054CF8A8) 
          0x73CB7444 PreBindAssemblyEx+0x398c4 in clr.dll (+0xd7444) (0x054CFC68) 
          0x73CB7035 PreBindAssemblyEx+0x394b5 in clr.dll (+0xd7035) (0x054CFD64) 
          0x73CB6B21 PreBindAssemblyEx+0x38fa1 in clr.dll (+0xd6b21) (0x054CFDD4)

**Comment by Tomasak** [comment]
crash related to dotnet.
can't also repro on clean prece copy.

**Comment by SLdonny** [comment]
> can't also repro on clean prece copy.
wym by that and thanks, wa am i supposed to do updated dotnet? pretty sure i got the lastest
 
also managed to get a dump file would tht help?

**Comment by Tomasak** [comment]
This is for issues caused by FusionFix, not fix your IV copy repo

**Comment by SLdonny** [comment]
how is it not fusion fix, game loads fine when the files are not in my root folder??

**Comment by ThirteenAG** [comment]
1. Fusion fix is not compatible with 1.0.7.0
2. Fusion fix is not compatible with your dotnet stuff or vice versa.

What do you realistically expect to happen with the issue nobody is able to reproduce but you?

Figure out which dotnet thing crashes as indicated in your crash log, compile it from source, run the game under debugger and you should be able to determine where it crashes and why.

**Comment by RecklessGlue540** [comment]
.asi mods can conflict, it's probably not FusionFix's fault of the crash, but maybe the fault of combining Fusion with Scripthook.net.

Scripthook.net needs the fixing. 
Which it's most likely not going to get since it's long abandoned.

You may try [this fork](https://github.com/Tomasak/gta4_scripthookdotnet/releases/tag/release) that adds partial support for the Complete Edition and fixes it's long standing and annoying rain bug (which was always THE problem with .net scripthook btw), but it was fixed and partially adapted for the Complete Edition of the game ONLY, and any issues that may arise from running it on older patches, you shouldn't expect to ever see fixed. 
It's not really their job ensuring compatibility with every modification out there. Especially with pretty ancient stuff. It may have some good stuff made for, but doesn't hide the fact that it's wayy too old and being probably not the easiest thing to fix and adapt to newer versions.

**Comment by SLdonny** [comment]
sadly its still not working thank you anyways dudes, i downloaded a fusion fix fork by zolika working now, cant enjoy the new feautures tho :(
