### ISSUE TITLE
Hard shadow LOD "line" around the player

### ISSUE THREAD

**Issue by Spoggi99** [ThirteenAG/GTAIV.EFLC.FusionFix#710]
### Game version this happens in

v1.2.0.59

### What area of the game

I haven't played for a while (last version I used was v2.5.6), and now I notice a very hard line in the sun's shadow in front of the player in the latest version of FusionFix. This is especially noticeable when leaving the safe house in Broker at the beginning of the game.

You can see this line moving with the player in this [video](https://youtu.be/FfRZY2issEw).

It happens with every Shadow Filter setting.

### What should happen

Shadows should not change their "LOD" in front of the player, and transitions should be smoother.

### Last working version

v2.5.6

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Parallellines0451** [comment]
Did you replace the stipple.wtd that comes with FusionFix by accident?

**Comment by Spoggi99** [comment]
> Did you replace the stipple.wtd that comes with FusionFix by accident?

No, I tested it with a vanilla version of GTA IV + Fusion Fix on two PCs and both had this issue. I didn't touch stipple.wtd.

**Comment by LawrikLawrence** [comment]
Should be noted that shadows act fine after changing the Shadow Quality settings back and forth. See[ this Reddit post](https://www.reddit.com/r/GTAIV/comments/1hodxjh/how_do_i_fix_this_shadow_bug/).

**Comment by Parallellines0451** [comment]
I can't reproduce this in a clean copy of the game from Steam with only FusionFix installed.

Are you sure that there are absolutely no other mods installed or leftovers of previous game installations? What are your hardware specifications? Did you download FusionFix from here or someplace else? What happens if you put [this file](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/blob/main/resources/pc/textures/stipple.wtd) in update/pc/textures?

**Comment by sh30g0r4d** [comment]
Not sure if this could help but just in case i remember having an issue with shadows in an older version of fusionfix which i got fixed by replacing vanilla shaders directly with the fusionfix ones instead of just putting them on the update folder

**Comment by Spoggi99** [comment]
> Are you sure that there are absolutely no other mods installed or leftovers of previous game installations?

The only mods that were installed when the problem first occurred were the Radio Downgrader and DXVK along with these startup options: "-availablevidmem 16376 -nomemrestrict -norestrictions". However, I have since completely reinstalled the game and can confirm that the problem is still there. In fact, this harsh "shadow transition line" is even visible in a completely vanilla installation of GTA IV, albeit very faint and barely noticeable if you're not looking for it.
As you can see in [this screenshot](https://github.com/user-attachments/assets/bb1ac431-c2af-4582-a20b-6f7ca9ef52f2), there is a line where the grid shadow becomes invisible.

Also, with Fusion Fix installed, I was able to temporarily "fix" the problem by toggling the shadow quality back and forth as @LawrikLawrence recommended. However, the grid shadows are completely invisible after switching back and forth. While it makes the harsh line disappear, I don't think it's a real fix, as the grid shadows should be visible in my opinion.
It's a little hard to explain, so [here is a video](https://youtu.be/2Fu927v0URQ).

I also noticed that this "line" moves when the camera perspective changes, if that helps to narrow down the problem ([here is a video](https://youtu.be/pu5FXu7H7sQ)).

PS: Sorry for all the videos, I hope they are at least somewhat helpful...

> What are your hardware specifications?

Win 11 Pro
CPU: i7 12700K
GPU: RTX 4080 Super with latest Nvidia driver
RAM: 32GB DDR4-3600

> Did you download FusionFix from here or someplace else?

I always download FusionFix directly from here on GitHub

> What happens if you put this file in update/pc/textures?

Unfortunately it doesn't change anything.

**Comment by Parallellines0451** [comment]
That's very odd, it's as if the game isn't loading the stipple texture properly until a device reset occurs. What happens if you replace it directly in the pc/textures folder, rather than update/pc/textures?

> and DXVK along with these startup options: "-availablevidmem 16376 -nomemrestrict -norestrictions"

You don't really need to use any startup parameters unless the game fails to recognize more than 512 MB of VRAM, which in that case you only need `-availablevidmem` and nothing else. There have also been reports of problems in GTA IV with DXVK 2.5.2, so try to use the previous version or the latest artifact from their repository instead.

> However, the grid shadows are completely invisible after switching back and forth. While it makes the harsh line disappear, I don't think it's a real fix, as the grid shadows should be visible in my opinion.

This is normal, however. It's how contact hardening shadows are supposed to work, they get softer the farther they are from the caster.

**Comment by LawrikLawrence** [comment]
Okay, so DXVK 2.5.2 is the cause. I downgraded to DXVK 2.5.1 and the shadows are perfectly fine. Earlier I tested a clean GTA 4 install with the latest DXVK and the issue still appeared. I don't think FusionFix has anything to do with this bug.
I don't know if it'll work for @Spoggi99 because in his case the bug behaved slightly different from [how it behaved for me](https://www.reddit.com/r/GTAIV/comments/1hodxjh/how_do_i_fix_this_shadow_bug/).

**Comment by Spoggi99** [comment]
Thank you @LawrikLawrence! I can confirm that the shadow transition is _almost_ completely invisible when using either DXVK 2.5.1 or its latest artifact - at least when using CHSS. With Shadow Filtering set to "Hard", the transition line is still faintly visible if you really look for it, as shown [here](https://github.com/user-attachments/assets/e7a57128-a560-45c9-8970-295634fc0bc4) or in [this video](https://www.youtube.com/watch?v=_QbVLHuvIHk) (top of the screen). 

However, since this is similar to what happens in a completely vanilla version of GTA IV, as seen in my [previous screenshot](https://github.com/user-attachments/assets/bb1ac431-c2af-4582-a20b-6f7ca9ef52f2), I don’t believe this issue is related to Fusion Fix or DXVK.

Apologies for creating an issue that wasn’t connected to Fusion Fix after all! I hope either of you you didn't waste too much time on this!

@Parallellines0451 Thank you for your suggestion about the startup parameters! There’s a lot of information on this topic, and it’s not always clear which parameters are necessary, so I really appreciate your input!

Thanks again for your time and effort in addressing this, and I'm sorry it wasn't related to Fusion Fix after all!
